### PR TITLE
Upgrade to support angular 8

### PR DESCRIPTION
**Pull request by TPJ11**
Upgraded package to run on angular 8

Changed version to V4 as changed the peerDependencies to require V8 +

Have set the new opts on ViewChild to static false this means it will changed behaviour when ivy becomes the default but should not break anything

### CODE REVIEW

**Comment by chadbr** [comment]
@TPJ11 planning to update based on comments?

**Comment by chadbr** [comment]
@crooksey any roadblocks here or?

**Comment by mmalomo** [comment]
Any thoughts?

**Comment by chadbr** [comment]
@crooksey @Zak-C would you guys like some more contributors? It doesn't look you guys are wanting to maintain this anymore? Happy to help if it helps you guys...

**Comment by crooksey** [comment]
I am not a maintainer, I woukd happily become one, I am the only other person other than Zack who has contributed, Zack if your happy to give me access to approve PR's I can do and prepare npm releases. I use this library commercially and also maintain a private fork.Sent from Android. 
-------- Original message --------From: chadbr <notifications@github.com> Date: 20/06/2019  18:57  (GMT+02:00) To: Zak-C/ngx-loading <ngx-loading@noreply.github.com> Cc: Luke Crooks <luke@crooksey.org>, Mention <mention@noreply.github.com> Subject: Re: [Zak-C/ngx-loading] Upgrade to support angular 8 (#91) @crooksey @Zak-C would you guys like some more contributors? It doesn't look you guys are wanting to maintain this anymore? Happy to help if it helps you guys...

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Zak-C/ngx-loading/pull/91?email_source=notifications\u0026email_token=AAGSTCYQJBAOXEDTZNSVLLTP3OSGBA5CNFSM4HRCVEH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYF3DII#issuecomment-504082849",
"url": "https://github.com/Zak-C/ngx-loading/pull/91?email_source=notifications\u0026email_token=AAGSTCYQJBAOXEDTZNSVLLTP3OSGBA5CNFSM4HRCVEH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYF3DII#issuecomment-504082849",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
Sent via Migadu.com, world's easiest email hosting

**Comment by chadbr** [comment]
ok -- @Zak-C hasn't been on github since Dec - so I'm guessing he's not going to maintain anymore.

Maybe we need to fork? no idea...

giphy

**Comment by crooksey** [comment]
I will email him Monday and see if we can sort. Sent from Samsung Mobile on O2
-------- Original message --------From: chadbr <notifications@github.com> Date: 20/06/2019  19:29  (GMT+02:00) To: Zak-C/ngx-loading <ngx-loading@noreply.github.com> Cc: Luke Crooks <luke@crooksey.org>, Mention <mention@noreply.github.com> Subject: Re: [Zak-C/ngx-loading] Upgrade to support angular 8 (#91) ok -- @Zak-C hasn't been on github since Dec - so I'm guessing he's not going to maintain anymore.
Maybe we need to fork? no idea...


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Zak-C/ngx-loading/pull/91?email_source=notifications\u0026email_token=AAGSTC7UYSGRJO4CZCOEW43P3OV7TA5CNFSM4HRCVEH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYF546A#issuecomment-504094328",
"url": "https://github.com/Zak-C/ngx-loading/pull/91?email_source=notifications\u0026email_token=AAGSTC7UYSGRJO4CZCOEW43P3OV7TA5CNFSM4HRCVEH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYF546A#issuecomment-504094328",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
Sent via Migadu.com, world's easiest email hosting

**Comment by obraeckman** [comment]
Hello @crookse

Any news from @Zak-C ?

**Comment by crooksey** [comment]
No, I will fork and publish to npm this week. Sent from Samsung Mobile on O2
-------- Original message --------From: obraeckman <notifications@github.com> Date: 01/07/2019  06:46  (GMT+00:00) To: Zak-C/ngx-loading <ngx-loading@noreply.github.com> Cc: Luke Crooks <luke@crooksey.org>, Mention <mention@noreply.github.com> Subject: Re: [Zak-C/ngx-loading] Upgrade to support angular 8 (#91) Hello @crookse
Any news from @Zak-C ?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Zak-C/ngx-loading/pull/91?email_source=notifications\u0026email_token=AAGSTC6STLPBJVDWZJ33VO3P5GK3RA5CNFSM4HRCVEH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODY5BTLY#issuecomment-507124143",
"url": "https://github.com/Zak-C/ngx-loading/pull/91?email_source=notifications\u0026email_token=AAGSTC6STLPBJVDWZJ33VO3P5GK3RA5CNFSM4HRCVEH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODY5BTLY#issuecomment-507124143",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
Sent via Migadu.com, world's easiest email hosting

**Comment by Zak-C** [comment]
Sorry all, I have been extremely busy of late, but will aim to resolve this issue within the next week or so. Thanks

**Comment by ceilino** [comment]
@crooksey  @Zak-C  thanks a lot, the fix is now urgent. I'm stuck with the angular update of the project and blocks another one :(

If any help is need please let me know.

Also, how does the component will behave if angular 9 comes out in 2-3 months.
would make better sense to say angular '>6.0.0' ?

**Comment by mmalomo** [comment]
@ceilino you can upgrade to https://napster2210.github.io/ngx-spinner/
It is very similar but with more options

**Comment by obraeckman** [comment]
@Zak-C any news ?

**Comment by obraeckman** [comment]
Has anyone forked and published this in NPM by any chance ? 
I love this spinner and want to keep it if possible... don't think @Zak-C  is about to approve the pull request any time soon...

**Comment by ceilino** [comment]
@obraeckman  I unfortunately could not wait any longer, therefore I took the advice from mmalomo :) migration was quite fast.

>  you change to https://napster2210.github.io/ngx-spinner/
> It is very similar but with more options

It works on latest angular and has cool options.

**Comment by obraeckman** [comment]
> @obraeckman I unfortunately could not wait any longer, therefore I took the advice from mmalomo :) migration was quite fast.
> 
> > you change to https://napster2210.github.io/ngx-spinner/
> > It is very similar but with more options
> 
> It works on latest angular and has cool options.

Indeed. I just did the same with ngx-spinner... bye bye ngx-loading.

**Comment by pasevin** [comment]
oh how I wish this was merged and released @Zak-C, please spare us!

**Comment by Zak-C** [comment]
I had to make additional tweaks, but I have updated the code base to support both Angular 7 (v7.0.0) and Angular 8 (v8.0.0) and released to NPM.

**Pull request closed without merging**
