### PR TITLE
16.0 Updated version 

### PR DESCRIPTION
**Pull request by theodury**
This PR is for 

Upgrading dependencies to latest versions to support angular 16

### CODE REVIEW

**Comment by ozkoidi** [comment]
Can someone review and merge this please?

**Review by ozkoidi — APPROVED** [review]
Indentation changes made it a bit more difficult to review but the code looks good to me

**Review by ozkoidi — APPROVED** [review]

**Comment by ozkoidi** [comment]
pinging contributors @zak-c-lmk, @jerone, @crooksey and @Zak-C. Can someone check this small pull request please?

**Comment by Zak-C** [comment]
V16 now supported.

**Pull request closed without merging**
